### ISSUE TITLE
How fast to parse a text ?

### ISSUE THREAD

**Issue by mrahmadt** [akoumjian/datefinder#20]
Hello

I have this very small text and it seems it's very slow to parse it, am I doing something wrong?

```
text = "hello 2014/02/15 love you"

import datefinder

matches = datefinder.find_dates(text,False,False,True);

print "datefinder = "

for match in matches:
    if match.year>1800 :
        print match,match.year,match.month,match.day


$ time python test.py 
datefinder = 
2014-02-15 00:00:00 2014 2 15

real    0m1.380s
user    0m0.976s
sys 0m0.080s
```

**Comment by akoumjian** [comment]
I'm not sure what you're setup is, but this was the slowest run on my machine

```sh
datefinder =
2014-02-15 00:00:00 2014 2 15
python mini.py  0.08s user 0.07s system 74% cpu 0.204 total
```

I will say that datefinder is relatively slow because it uses a very large regex matching pattern. A majority of that time is probably compiling the pattern. I could look into doing that on import. I'm open to suggestions for optimizations.
